project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "0"
        href: Hands-on_exercise/Hands-on_exercise_00/Hands-on_exercise_00.html
      - text: "1: ggplot2 methods"
        href: Hands-on_exercise/Hands-on_exercise_01/Hands-on_exercise_01.html
      - text: "2: Beyond ggplot2 Fundamentals"
        href: Hands-on_exercise/Hands-on_exercise_02/Hands-on_exercise_02.html
      - text: "3-1: Programming Interactive Data Visualisation with R"
        href: Hands-on_exercise/Hands-on_exercise_03/Hands-on_exercise_03-1.html
      - text: "3-2: Programming Animated Statistical Graphics with R"
        href: Hands-on_exercise/Hands-on_exercise_03/Hands-on_exercise_03-2.html
      - text: "4-1: Visualising Distribution"
        href: Hands-on_exercise/Hands-on_exercise_04/Hands-on_exercise_04-1.html
      - text: "4-2: Visual Statistical Analysis"
        href: Hands-on_exercise/Hands-on_exercise_04/Hands-on_exercise_04-2.html
      - text: "4-3: Visualising Uncertainty"
        href: Hands-on_exercise/Hands-on_exercise_04/Hands-on_exercise_04-3.html
      - text: "4-4: Funnel Plots for Fair Comparisons"
        href: Hands-on_exercise/Hands-on_exercise_04/Hands-on_exercise_04-4.html
      - text: "5-1: Creating Ternary Plot with R"
        href: Hands-on_exercise/Hands-on_exercise_05/Hands-on_exercise_05-1.html
      - text: "5-2: Visual Correlation Analysis"
        href: Hands-on_exercise/Hands-on_exercise_05/Hands-on_exercise_05-2.html
      - text: "5-3: Heatmap for Visualising and Analysing Multivariate Data"
        href: Hands-on_exercise/Hands-on_exercise_05/Hands-on_exercise_05-3.html
      - text: "5-4: Visual Multivariate Analysis with Parallel Coordinates Plot"
        href: Hands-on_exercise/Hands-on_exercise_05/Hands-on_exercise_05-4.html
      - text: "5-5: Treemap Visualisation with R"
        href: Hands-on_exercise/Hands-on_exercise_05/Hands-on_exercise_05-5.html
      - text: "7: Visualising and Analysing Time-oriented Data"
        href: Hands-on_exercise/Hands-on_exercise_07/Hands-on_exercise_07.html
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: In-class_exercise/In-class_exercise_01.html
      - text: "In-class Exercise 2"
        href: In-class_exercise/In-class_exercise_02.html
      - text: "In-class Exercise 3"
        href: In-class_exercise/In-class_exercise_03.html
      - text: "In-class Exercise 4"
        href: In-class_exercise/In-class_exercise_04.html
      - text: "In-class Exercise 5"
        href: In-class_exercise/In-class_exercise_05.html
      - text: "In-class Exercise 6"
        href: In-class_exercise/In-class_exercise_06.html
      - text: "In-class Exercise 7"
        href: In-class_exercise/In-class_exercise_07.html
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take-home_exercise/Take-home_exercise_1.html
      - text: "Take-home Exercise 2"
        href: Take-home_exercise/Take-home_exercise_2.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

