project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "0"
        href: Hands-on exercise/Hands-on exercise 00/Hands-on exercise 00.html
      - text: "1: ggplot2 methods"
        href: Hands-on exercise/Hands-on exercise 01/Hands-on exercise 01.html
      - text: "2: Beyond ggplot2 Fundamentals"
        href: Hands-on exercise/Hands-on exercise 02/Hands-on exercise 02.html
      - text: "3-1: Programming Interactive Data Visualisation with R"
        href: Hands-on exercise/Hands-on exercise 03/Hands-on exercise 03-1.html
      - text: "3-2: Programming Animated Statistical Graphics with R"
        href: Hands-on exercise/Hands-on exercise 03/Hands-on exercise 03-2.html
      - text: "4-1: Visualising Distribution"
        href: Hands-on exercise/Hands-on exercise 04/Hands-on exercise 04-1.html
      - text: "4-2: Visual Statistical Analysis"
        href: Hands-on exercise/Hands-on exercise 04/Hands-on exercise 04-2.html
      - text: "4-3: Visualising Uncertainty"
        href: Hands-on exercise/Hands-on exercise 04/Hands-on exercise 04-3.html
      - text: "4-4: Funnel Plots for Fair Comparisons"
        href: Hands-on exercise/Hands-on exercise 04/Hands-on exercise 04-4.html
      - text: "5-1: Creating Ternary Plot with R"
        href: Hands-on exercise/Hands-on exercise 05/Hands-on exercise 05-1.html
      - text: "5-2: Visual Correlation Analysis"
        href: Hands-on exercise/Hands-on exercise 05/Hands-on exercise 05-2.html
      - text: "5-3: Heatmap for Visualising and Analysing Multivariate Data"
        href: Hands-on exercise/Hands-on exercise 05/Hands-on exercise 05-3.html
      - text: "5-4: Visual Multivariate Analysis with Parallel Coordinates Plot"
        href: Hands-on exercise/Hands-on exercise 05/Hands-on exercise 05-4.html
      - text: "5-5: Treemap Visualisation with R"
        href: Hands-on exercise/Hands-on exercise 05/Hands-on exercise 05-5.html
      - text: "7: Visualising and Analysing Time-oriented Data"
        href: Hands-on exercise/Hands-on exercise 07/Hands-on exercise 07.html
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: In-class exercise/In-class exercise 01.html
      - text: "In-class Exercise 2"
        href: In-class exercise/In-class exercise 02.html
      - text: "In-class Exercise 3"
        href: In-class exercise/In-class exercise 03.html
      - text: "In-class Exercise 4"
        href: In-class exercise/In-class exercise 04.html
      - text: "In-class Exercise 5"
        href: In-class exercise/In-class exercise 05.html
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take-home exercise/Take-home exercise 1.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

